### ISSUE TITLE
Possibility to turn off system logging but not sonde log

### ISSUE THREAD

**Issue by yt1niv** [projecthorus/radiosonde_auto_rx#103]
Hi,

it is possible to add option to turn off system related logging, but to be able to log sondes?
Today I erased over 50000 logs and that is just for several days of usage! Because I have qrm on several freqs and it logs it every few seconds...

Regards,
Ivan, yt1niv

**Comment by darksidelemm** [comment]
At the moment, no, but there's definitely some improvements that could be made to clean up the system log a bit.
By 50000 logs, do you mean log files, or log *lines*? 
My latest system log is ~130k lines, and about 13MB, which is not terrible. Perhaps logrotate would be useful here.

Also just to confirm, are you running the latest version?

**Comment by yt1niv** [comment]
Yes, 50000 log files! Some of them were 0kb, most of them was 1kb and several with 100 to 600 kb...
Updated yesterday to latest version (and still M10 doesnt work :D ) and had also many files from then..

**Comment by darksidelemm** [comment]
This is definitely odd behaviour. Telemetry log files are only opened and written when valid telemetry arrives, and system log files are only opened when auto_rx is started.

The fat you have that many log files suggests auto_rx.py is crashing out in some very bad way, and it would be good to know further details why.
If you're running auto_rx using systemd, I'd suggest looking at the systemd log output using:
sudo journalctl -u auto_rx.service -f -n

**Comment by darksidelemm** [comment]
Also... M10 support is still in development, and is not in the Master branch yet. We're currently checking that some of the changes don't degrade performance for other radiosonde types.

**Comment by darksidelemm** [comment]
Any updates on this yt1niv? Without further information on why auto_rx is crashing this one is difficult to meaningfully resolve...

**Comment by darksidelemm** [comment]
OK.. in this case I'm going to close off this issue.
If you encounter this problem again, feel free to raise another issue.
