### ISSUE TITLE
RS41 aux data

### ISSUE THREAD

**Issue by TheSkorm** [projecthorus/radiosonde_auto_rx#119]
We should be logging and reporting aux data for RS41s

**Comment by TheSkorm** [comment]
Some samples recorded for testing

**Comment by rs1729** [comment]
If there are more than 1 aux-string in one frame, it overwrites the string with the last aux-message, however if a previous one was longer, the leftovers are still visible. (also the last character is chopped.)

rs41dm_iq.c was prepared for aux and conf data. I added json-output for aux-data, so you can compare.

**Comment by TheSkorm** [comment]
Nice catch @rs1729 ; My real world sample only had one sensor so didn't have this issue. I'll patch this later. It should be as simple as adding a null char after the loop. I'm not sure how we should handle multiple aux frames though. I guess we could make the JSON have an array of aux data but I'm not sure how we'd handle that with the logging

**Comment by rs1729** [comment]
Here
https://github.com/rs1729/RS/blob/master/demod/rs41dm_iq.c
I concatenate the aux-strings, using '#' as separator.

**Comment by darksidelemm** [comment]
Resolved by https://github.com/projecthorus/radiosonde_auto_rx/pull/138
