### ISSUE TITLE
Last received sonde should be on top, is now at the bottom.

### ISSUE THREAD

**Issue by zanco** [projecthorus/radiosonde_auto_rx#171]
Hi, if you receive more as 5 sondes the last received sonde does not fit in the top view. You have to scroll the window one line down, to see the latest sonde, but then the window refreshes and this sonde is out of the view.

Would be easier if the last sonde was shown on top of the list.

Thanks,
Ben
![moreas5sondesreceived](https://user-images.githubusercontent.com/4477734/57463297-c9e02f80-727a-11e9-8886-16f08beef377.JPG)

**Comment by darksidelemm** [comment]
Resolved in https://github.com/projecthorus/radiosonde_auto_rx/pull/172.

The 'Age' field in the table now has a sort option. If you click the age column header, it will sort by age.

Please test!

**Comment by darksidelemm** [comment]
https://github.com/projecthorus/radiosonde_auto_rx/releases/tag/v1.1.0
