### ISSUE TITLE
Program stays on decoding but nothing is ever decoded

### ISSUE THREAD

**Issue by nunomiguelferreira** [projecthorus/radiosonde_auto_rx#201]
Hello, so the problem is when I get an RS41 sonde locked and starting to decode, it just tries to decode but nothing happens, it always gives a timeout. I have a print down below:

https://ibb.co/K2nWXDX

I know that the sonde and the RTL is working since under windows with SDR Sharp and RS41 tracker it works.

This problem happens using a RPI3 with raspbian.

Any suggestion appreciated and thank you for your time.

**Comment by darksidelemm** [comment]
A few questions:
- Is this happening consistently with all detected sondes?
- Are you using the normal or experimental decoders? If you have even a small PPM offset on your SDR, detection will still work but decoding can be severely impacted. Try using the experimental decoder which is far more tolerant of drift: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/station.cfg.example#L416
If you are still having issues, enable some of the debug options:
https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/station.cfg.example#L349
The decoded audio (For the normal decoder) and decoded IQ (for the experimental decoder) can help with debugging.
