### ISSUE TITLE
Radiosonde Support - LMS-X (New LMS sonde)

### ISSUE THREAD

**Issue by miweber67** [projecthorus/radiosonde_auto_rx#202]
I observed a sonde signal today that looked somewhat like an LMS6-400 and was identified as an LMS6-400 by the software but was NOT an LMS6-400; the decoder did not recover any data, and upon listening to the signal, it did not have the typical 1Hz modulation pulse typical of the LMS6.

I did grab an IQ recording of the sonde, but as there were three (3!) other sondes in the air simultaneously, my bandwidth was 5MHz and the 10 minute raw recording is 26GB. That may prove difficult to share, but I am open to ideas. I might be able to create a GRC graph that will isolate a more reasonable chunk of spectrum to create a smaller file without destroying whatever resolution is needed to do testing.

**Comment by darksidelemm** [comment]
If you can narrow it down to the smallest necessary bandwidth that would be useful. Also perhaps a FM-demodulated copy also, which can be run against the other demodulators available from @rs1729's upstream repo.

Where are you located? It may be possible to find out what sonde type it is just by looking at the station information @rs1729 has collated here: https://github.com/rs1729/RS/issues/15

**Comment by rs1729** [comment]
Yes, IQ-recording of the relevant bandwidth would be good. Or maybe you trim the IQ-recording to 10 sec where the signal is strong. (You can use sox.) 10 sec or maybe 5 sec for a first inspection.
If it looks like a LMS6, you can try lmsXdm_dft.c from
https://github.com/rs1729/RS/tree/master/demod/
for the FM-demodulated audio.
A while ago there were (test?) flights in Canada of something that looked like LMS6, and actually it was very similar, only the frame structure was a bit different.

**Comment by darksidelemm** [comment]
Aha... they launch all sorts of things out of Washington Dulles... For
example the 'unknown' DFMxC sonde that is currently in the air (possibly a
DFM17).

**Comment by miweber67** [comment]
As an aside... is it normal for RS41 sondes to have two transmitters on them? I have two RS41-NGs that are 0.9 MHz apart but are reporting essentially identical positions; the altitude is different by a fraction of a meter, but that's about it.

**Comment by rs1729** [comment]
Sometimes two radiosondes or more are launched together for comparison:
https://www.vaisala.com/sites/default/files/documents/VN184_16_WMOIntercomparisonofRadiosondeSystemsinChina.pdf

**Comment by darksidelemm** [comment]
If you're seeing sondes from the NWS site just north of Washington-Dulles Airport, then it's likely as @rs1729 says. It appears to be some kind of experimentation site for the NWS, hence the large range of radiosonde types that have been sighted from there.

**Comment by miweber67** [comment]
Interesting! It could be I just don't have enough receivers to cover them all, and when one drops out due to tree shadowing, I pick up a twin from a previous launch. I have only two going. If multi-sonde single-stream decoding works out, I'll have to set up an airspy to cover the entire band and just let it go for a while. :-)

Here are two pairs of "odd twins" from today:

http://sondehub.org/P4428205
http://sondehub.org/P4428155

http://sondehub.org/DFMxC-18085096
http://sondehub.org/DFMxC-18085708

**Comment by TheSkorm** [comment]
I was lucky enough to watch one of the launches that was an ozone sensor/box with both an RS41 and a RS92. It's fairly common when testing new radiosonde equipment according to the local staff. They use the results as a baseline when they are comparing historic data.

General approach to receiving multiple sondes has been just adding more SDRs because developing a receiving chain for decoding multiple sondes on the same SDR is non trival and buying a $20 SDR is much easier solution :P

**Comment by darksidelemm** [comment]
I've obtained the IQ recordings from @miweber67 and have extracted some FM demodulated samples of the two 'LMS6' sondes, along with another 'unknown'. The two 'LMS6' samples were from around 404 MHz, and both match as a LMS6 using dft_detect. The other 'unknown' signal was at 406 MHz, and might not even be a sonde.
The samples are here: https://rfhead.net/sondes/unknown_washington/

The original 10 second IQ sample is also there, though it's still being uploaded.

**Comment by rs1729** [comment]
lmsXdm_dft.c decodes

lms6_unknown_1:
 (8079672)  [ 5516]  lat: 38.963919  lon: -77.080528  alt: 21499.40m   vH: 5.0m/s  D: 298.1  vV: 5.4m/s  [OK]
 (8079672)  [ 5517]  lat: 38.963929  lon: -77.080579  alt: 21504.98m   vH: 4.6m/s  D: 283.3  vV: 5.8m/s  [OK]
 (8079672)  [ 5518]  lat: 38.963923  lon: -77.080636  alt: 21510.19m   vH: 5.5m/s  D: 261.1  vV: 5.4m/s  [OK]
 (8079672)  [ 5509]  lat: 38.963763  lon: -77.080091  alt: 21464.04m   vH: 8.5m/s  D: 310.3  vV: 5.3m/s  [OK]
 (8079672)  [ 5510]  lat: 38.963800  lon: -77.080168  alt: 21469.37m   vH: 7.7m/s  D: 301.6  vV: 5.2m/s  [OK]
 (8079672)  [ 5511]  lat: 38.963817  lon: -77.080241  alt: 21474.19m   vH: 6.6m/s  D: 291.1  vV: 4.7m/s  [OK]
 (8079672)  [ 5512]  lat: 38.963823  lon: -77.080306  alt: 21479.38m   vH: 5.5m/s  D: 279.3  vV: 4.9m/s  [OK]
 (8079672)  [ 5513]  lat: 38.963837  lon: -77.080367  alt: 21484.61m   vH: 5.6m/s  D: 290.2  vV: 5.3m/s  [OK]
 (8079672)  [ 5514]  lat: 38.963862  lon: -77.080423  alt: 21489.48m   vH: 5.9m/s  D: 302.6  vV: 5.0m/s  [OK]
 (8079672)  [ 5515]  lat: 38.963893  lon: -77.080476  alt: 21494.10m   vH: 6.0m/s  D: 308.5  vV: 4.8m/s  [OK]
 (8079672)  [ 5516]  lat: 38.963919  lon: -77.080528  alt: 21499.40m   vH: 5.0m/s  D: 298.1  vV: 5.4m/s  [NO]

lms6_unknown_2:
 (8079827)  [ 5435]  [NO]
 (8079827)  [ 5426]  lat: 38.963818  lon: -77.080160  alt: 21467.60m   vH: 8.4m/s  D: 304.9  vV: 5.1m/s  [OK]
 (8079827)  [ 5427]  lat: 38.963832  lon: -77.080232  alt: 21473.00m   vH: 6.8m/s  D: 296.8  vV: 5.0m/s  [OK]
 (8079827)  [ 5428]  lat: 38.963837  lon: -77.080296  alt: 21478.15m   vH: 5.6m/s  D: 283.7  vV: 5.0m/s  [OK]
 (8079827)  [ 5429]  lat: 38.963843  lon: -77.080346  alt: 21484.15m   vH: 5.3m/s  D: 290.6  vV: 5.6m/s  [OK]
 (8079827)  [ 5430]  lat: 38.963862  lon: -77.080399  alt: 21489.31m   vH: 5.6m/s  D: 301.5  vV: 5.3m/s  [OK]
 (8079827)  [ 5431]  lat: 38.963891  lon: -77.080450  alt: 21494.13m   vH: 5.8m/s  D: 308.3  vV: 5.0m/s  [OK]
 (8079827)  [ 5432]  lat: 38.963915  lon: -77.080501  alt: 21499.26m   vH: 4.9m/s  D: 294.6  vV: 5.4m/s  [OK]
 (8079827)  [ 5433]  lat: 38.963922  lon: -77.080554  alt: 21504.74m   vH: 4.8m/s  D: 270.5  vV: 5.6m/s  [OK]
 (8079827)  [ 5434]  lat: 38.963914  lon: -77.080612  alt: 21509.95m   vH: 5.5m/s  D: 256.9  vV: 5.2m/s  [OK]

Looks like the recording is cyclic in time..
The lmsX (working title) is similar to the LMS6-403MHz, maybe a new version (would be time an update). Have encountered this type in february, probably test flights in Canada.

**Comment by rs1729** [comment]
2x M10 in us_sondes_404mhz_fs_5mhz_float.raw

./rs_multi --m10 -0.28034 - 5000000 32 us_sondes_404mhz_fs_5mhz_float.raw
<0> Mon 2019-08-26 20:45:19.000  lat: 38.97492  lon: -77.07311  alt: 1887.39   vH: 5.5  D: 340.8  vV: -3.5   SN: 811 2 11745  #  [OK]  T=12.6C 
<0> Mon 2019-08-26 20:45:20.000  lat: 38.97496  lon: -77.07314  alt: 1883.80   vH: 5.2  D: 329.6  vV: -3.7   SN: 811 2 11745  #  [OK]  T=12.5C 
<0> Mon 2019-08-26 20:45:21.000  lat: 38.97500  lon: -77.07317  alt: 1880.10   vH: 5.7  D: 323.6  vV: -3.6   SN: 811 2 11745  #  [OK]  T=12.5C 
<0> Mon 2019-08-26 20:45:22.000  lat: 38.97505  lon: -77.07322  alt: 1876.54   vH: 6.2  D: 323.1  vV: -3.5   SN: 811 2 11745  #  [OK]  T=12.6C 
<0> Mon 2019-08-26 20:45:23.000  lat: 38.97509  lon: -77.07326  alt: 1873.08   vH: 6.6  D: 325.1  vV: -3.4   SN: 811 2 11745  #  [OK]  T=12.6C 
<0> Mon 2019-08-26 20:45:24.000  lat: 38.97514  lon: -77.07330  alt: 1869.63   vH: 6.7  D: 327.7  vV: -3.5   SN: 811 2 11745  #  [OK]  T=12.6C 
<0> Mon 2019-08-26 20:45:25.000  lat: 38.97519  lon: -77.07334  alt: 1866.13   vH: 6.3  D: 332.6  vV: -3.5   SN: 811 2 11745  #  [OK]  T=12.6C 
<0> Mon 2019-08-26 20:45:26.000  lat: 38.97524  lon: -77.07337  alt: 1862.62   vH: 5.8  D: 340.1  vV: -34.1   SN: 811 2 11745  #  [NO]  T=12.7C 

./rs_multi --m10 -0.36 - 5000000 32 us_sondes_404mhz_fs_5mhz_float.raw
<0> Mon 2019-08-26 20:45:20.000  lat: 38.97495  lon: -77.07316  alt: 1880.51   vH: 5.9  D: 324.5  vV: -3.6   SN: 811 2 11760  #  [OK]  T=12.5C 
<0> Mon 2019-08-26 20:45:21.000  lat: 38.97499  lon: -77.07321  alt: 1877.09   vH: 6.4  D: 324.1  vV: -3.8   SN: 811 2 11760  #  [OK]  T=12.5C 
<0> Mon 2019-08-26 20:45:22.000  lat: 38.97504  lon: -77.07325  alt: 1873.94   vH: 6.9  D: 325.5  vV: -3.7   SN: 811 2 11760  #  [OK]  T=12.4C 
<0> Mon 2019-08-26 20:45:23.000  lat: 38.97509  lon: -77.07329  alt: 1870.67   vH: 7.0  D: 328.7  vV: -3.6   SN: 811 2 11760  #  [OK]  T=12.4C 
<0> Mon 2019-08-26 20:45:24.000  lat: 38.97514  lon: -77.07333  alt: 1867.38   vH: 6.7  D: 330.9  vV: -3.5   SN: B13 2 11760  #  [NO]  T=12.5C 
<0> Mon 2019-08-26 20:45:26.000  lat: 38.97524  lon: -77.07339  alt: 1860.83   vH: 5.6  D: 343.7  vV: -3.5   SN: 811 2 11760  #  [NO]  T=12.7C 
<0> Mon 2019-08-26 20:45:27.000  lat: 38.97529  lon: -77.07340  alt: 1857.56   vH: 5.8  D: 352.8  vV: -3.5   SN: 811 2 11760  #  [OK]  T=12.6C 
<0> Mon 2019-08-26 20:45:28.000  lat: 38.97534  lon: -77.07341  alt: 1854.22   vH: 6.2  D: 359.2  vV: -3.6   SN: 811 2 11760  #  [OK]  T=12.5C

**Comment by miweber67** [comment]
The signal that was being detected as an LMS6 by dft_detect is at +2.262 MHz from the center of 404MHz, or 406.262. It fades like a sonde...

**Comment by rs1729** [comment]
There are 2 LMS-like signals (detected as LMS6):
404000+122 kHz = 404122 kHz (122kHz/5MHz=0.0244): lmsX_1 (8079672)
404000+633 kHz = 404633 kHz (633kHz/5MHz=0.1266): lmsX_2 (8079827)
as decoded above (lmsXdm_dft.c). Same header as LMS6, but a bit different frame structure.

And two M10 at 402.6MHz and 402.2MHz.

Don't know about the signals above 406 MHz.

**Comment by darksidelemm** [comment]
Hopefully these new LMS sondes are smaller than the old one! And about time they refreshed the design, the LMS6 is getting a bit old!

**Comment by rs1729** [comment]
With

cat us_sondes_404mhz_fs_5mhz_float.raw | csdr shift_addition_cc -0.02428 | csdr fir_decimate_cc 100 0.005 HAMMING | csdr bandpass_fir_fft_cc -0.10 0.10 0.05 | csdr fmdemod_quadri_cf | csdr limit_ff | csdr convert_f_u8 | sox -t raw -r 50000 -b 8 -e unsigned-integer - -t wav lmsX_20190226_404122kHz.wav

cat us_sondes_404mhz_fs_5mhz_float.raw | csdr shift_addition_cc -0.12634 | csdr fir_decimate_cc 100 0.005 HAMMING | csdr bandpass_fir_fft_cc -0.10 0.10 0.05 | csdr fmdemod_quadri_cf | csdr limit_ff | csdr convert_f_u8 | sox -t raw -r 50000 -b 8 -e unsigned-integer - -t wav lmsX_20190226_404633kHz.wav


you can FM-demodulate the two LMS-signals and save to wav-audio (8 bit, 1 channel).
Could you (@miweber67 @darksidelemm) do this for the original recording (10min?).
Don't know if these LMS also drift as much as the LMS6, so maybe a wider lowpass filter would be better, but maybe you can try this first. A long recording would be interesting.

**Comment by darksidelemm** [comment]
It can also be re-played in GQRX and demodulated (which is how I produced those FM files).

@rs1729 Since it seems the header are the same, and hence both old and new LMS sondes show up as a LMS6, do you think it will be possible to auto-detect the frame format and decode appropriately? (like you have done for the RS41-SG/SGM)

**Comment by miweber67** [comment]
@rs1729 I will try to run the commands you posted and see what comes out... Is the audio recording sample I provider earlier also acceptable? If so I know how to do that already. :-)

**Comment by rs1729** [comment]
GPS data is different to LMS6, had another look at gpstime today, always something new, for lmsX it is a double/float64... added gpstime to the lmsX-decoder.

./lmsXdm_dft -v --ecc --vit lmsX_20190826_404122kHz.wav 
 (8079672)  [ 5509] Mon (20:45:18.031)  lat: 38.963763  lon: -77.080091  alt: 21464.04m   vH: 8.5m/s  D: 310.3  vV: 5.3m/s  [OK]
 (8079672)  [ 5510] Mon (20:45:19.031)  lat: 38.963800  lon: -77.080168  alt: 21469.37m   vH: 7.7m/s  D: 301.6  vV: 5.2m/s  [OK]
 (8079672)  [ 5511] Mon (20:45:20.031)  lat: 38.963817  lon: -77.080241  alt: 21474.19m   vH: 6.6m/s  D: 291.1  vV: 4.7m/s  [OK]
 (8079672)  [ 5512] Mon (20:45:21.032)  lat: 38.963823  lon: -77.080306  alt: 21479.38m   vH: 5.5m/s  D: 279.3  vV: 4.9m/s  [OK]
 (8079672)  [ 5513] Mon (20:45:22.032)  lat: 38.963837  lon: -77.080367  alt: 21484.61m   vH: 5.6m/s  D: 290.2  vV: 5.3m/s  [OK]
 (8079672)  [ 5514] Mon (20:45:23.032)  lat: 38.963862  lon: -77.080423  alt: 21489.48m   vH: 5.9m/s  D: 302.6  vV: 5.0m/s  [OK]
 (8079672)  [ 5515] Mon (20:45:24.032)  lat: 38.963893  lon: -77.080476  alt: 21494.10m   vH: 6.0m/s  D: 308.5  vV: 4.8m/s  [OK]
 (8079672)  [ 5516] Mon (20:45:25.032)  lat: 38.963919  lon: -77.080528  alt: 21499.40m   vH: 5.0m/s  D: 298.1  vV: 5.4m/s  [OK]
 (8079672)  [ 5517] Mon (20:45:26.032)  lat: 38.963929  lon: -77.080579  alt: 21504.98m   vH: 4.6m/s  D: 283.3  vV: 5.8m/s  [OK]
 (8079672)  [ 5518] Mon (20:45:27.032)  lat: 38.963923  lon: -77.080636  alt: 21510.19m   vH: 5.5m/s  D: 261.1  vV: 5.4m/s  [OK]

./lmsXdm_dft -v --ecc --vit lmsX_20190826_404633kHz.wav 
 (8079827)  [ 5425] Mon (20:45:18.024)  lat: 38.963778  lon: -77.080080  alt: 21462.31m   vH: 8.7m/s  D: 310.0  vV: 5.7m/s  [OK]
 (8079827)  [ 5426] Mon (20:45:19.024)  lat: 38.963818  lon: -77.080160  alt: 21467.60m   vH: 8.4m/s  D: 304.9  vV: 5.1m/s  [OK]
 (8079827)  [ 5427] Mon (20:45:20.024)  lat: 38.963832  lon: -77.080232  alt: 21473.00m   vH: 6.8m/s  D: 296.8  vV: 5.0m/s  [OK]
 (8079827)  [ 5428] Mon (20:45:21.024)  lat: 38.963837  lon: -77.080296  alt: 21478.15m   vH: 5.6m/s  D: 283.7  vV: 5.0m/s  [OK]
 (8079827)  [ 5429] Mon (20:45:22.024)  lat: 38.963843  lon: -77.080346  alt: 21484.15m   vH: 5.3m/s  D: 290.6  vV: 5.6m/s  [OK]
 (8079827)  [ 5430] Mon (20:45:23.024)  lat: 38.963862  lon: -77.080399  alt: 21489.31m   vH: 5.6m/s  D: 301.5  vV: 5.3m/s  [OK]
 (8079827)  [ 5431] Mon (20:45:24.024)  lat: 38.963891  lon: -77.080450  alt: 21494.13m   vH: 5.8m/s  D: 308.3  vV: 5.0m/s  [OK]
 (8079827)  [ 5432] Mon (20:45:25.024)  lat: 38.963915  lon: -77.080501  alt: 21499.26m   vH: 4.9m/s  D: 294.6  vV: 5.4m/s  [OK]
 (8079827)  [ 5433] Mon (20:45:26.024)  lat: 38.963922  lon: -77.080554  alt: 21504.74m   vH: 4.8m/s  D: 270.5  vV: 5.6m/s  [OK]
 (8079827)  [ 5434] Mon (20:45:27.024)  lat: 38.963914  lon: -77.080612  alt: 21509.95m   vH: 5.5m/s  D: 256.9  vV: 5.2m/s  [OK]

If you have csdr and sox installed and if the 10sec iq-recording us_sondes_404mhz_fs_5mhz_float.raw is part of the big 10min recording you have, same sample rate and center frequency, then it should  work. Could be that the signals drift out of the down converted window, but maybe if it is a new model, the drift is not as bad as for the LMS6.
Then you can try the lmsXdm_dft.c decoder in https://github.com/rs1729/RS/tree/master/demod as shown above. You can test the commands with the 10s-sample first.

**Comment by rs1729** [comment]
@darksidelemm 
I should better say, the sync word is the same, and that's what dft_detect is looking for, but the frame header is a bit different, and the reed-solomon codeword is not async to the frame, actually the new(?) structure is better for decoding.
And the GPS data is different, probably different chip. So you need different functions/calculations for position, so the situation is more like the M10 with the temporary gtop-chip before going back to the old format. But I would like to combine the lms-decoders (so you don't need two detectors), even if it would take two parts in the code.

Did not hear anything about a LMS6 successor. Graw and Meteomodem announced their new product some time ago, DFM-17 is doing test flights, but M20?
Looks like at Sterling they are testing different radiosonde types always in pairs. Wonder if the M10s could actually be M20. The second byte in the frame did give some type information, but maybe if the data is compatible to M10 it would stay the same. The DC area looks interesting for radiosonde hunters.

**Comment by miweber67** [comment]
Decodes:
https://pastebin.com/yM1WRfXf
https://pastebin.com/GMZStc0G

Sadly, most of the sondes fly out over Baltimore or the eastern portion of Maryland. Too far for me to drive, typically.

**Comment by rs1729** [comment]
If it decodes OK at fixed frequency, the frequency seems to be stable.
Is it possible for you to share the wav-files, the FM-demodulated files shouldn't be so big (though the original 5Msps file would be interesting). Or maybe @darksidelemm can put them on his website?

**Comment by darksidelemm** [comment]
Recordings are now here: https://rfhead.net/sondes/unknown_washington/

**Comment by rs1729** [comment]
Thank you.
I believe I missed the center frequency a bit, the first csdr-command was maybe 500Hz too low, the second (404.6MHz) 1kHz too low, it is more like I read from gqrx in 202#issuecomment-526788930.

404.1MHz-FM needs only a lowpass, for 404.6MHz-FM a 20Hz highpass improves decoding as well as a lowpass filter.

[lmsX_20190826_404122kHz_SN8079672.txt.gz](https://github.com/projecthorus/radiosonde_auto_rx/files/3563304/lmsX_20190826_404122kHz_SN8079672.txt.gz)
[lmsX_20190826_404633kHz_SN8079827.txt.gz](https://github.com/projecthorus/radiosonde_auto_rx/files/3563305/lmsX_20190826_404633kHz_SN8079827.txt.gz)

Yet they did not drift several kHz. Maybe compared to lower altitudes.

But I will test my dc/frequency correction a bit more. Seems to work for the rs41 now, will see.

**Comment by miweber67** [comment]
OK, I have coded up a spyserver client that is a drop-in replacement for rtl_fm (for the purposes of auto_rx, anyway), although I didn't get a chance to test it thoroughly during tonight's sonde launches. Hopefully tomorrow I will have some more chances to dial it in. I am able to use the airspy dongle when running the spyserver on x86 Linux, but I wasn't able to get it to serve up my RTL-SDR dongle for some reason. Will have to keep looking in to that.

With respect to rtl_power equivalence... the spyserver will send "fft data" as well as IQ data; I am thinking that perhaps a separate client could pull the fft data for the entire band and perform the services currently provided by rtl_power. If that works, then we're really close to being able to cover all 6 MHz of the US sonde band with a single dongle and decode as many sondes as they see fit to launch at once, bound only by CPU.

I started with the 'spyserver' code from here:

https://github.com/racerxdl/gr-osmosdr/tree/master/lib/spyserver

I removed all of the gnuradio dependencies, and removed almost all of the boost dependencies (only circular_buffer is left) and made other adjustments to get things working. Not sure how to cite/credit the original; new to github so looking for guidance there.

**Comment by rs1729** [comment]
Uploaded a combined lms6/X decoder lms6Xmod.
The baud rate is slightly different, and that's not all, sync-word has different period. (The new/unknown version is simpler. And there is space for more data, perhaps aux-data.)
If the decoder auto-detects, it could take one (or more) frames to set the new type. However you can force the type setting (--lms6 or --lmsX).

**Comment by darksidelemm** [comment]
The latest auto_rx testing branch now should support the LMSX variant, thanks to @rs1729's lms6Xmod decoder. The not-so-experimental fsk_demod chain seems to handle the different baud rate OK, but I don't know what the performance impacts of that are.

**Comment by darksidelemm** [comment]
Closing this now that support has been merged into the master branch: https://github.com/projecthorus/radiosonde_auto_rx/releases/tag/v1.2.0
