### ISSUE TITLE
Remove station_code setting in config.

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/radiosonde_auto_rx#220]
It appears to be causing too much trouble, with different station using different codes and then receiving the same sonde, resulting in multiple imet sondes appearing on the map.

Better to remove it entirely and then see if we end up with any sonde ID collisions.

**Comment by ZigiWalter** [comment]
(sorry for the messed we have caused with those IMETs... :-) )

**Comment by snh** [comment]
For reference, this has been completed by @darksidelemm in https://github.com/projecthorus/radiosonde_auto_rx/pull/221.

**Comment by snh** [comment]
This has landed in `master` and is available as part of v1.2.0 now. Please feel free to reopen if you come across any issues.
