### ISSUE TITLE
M10 in testing version auto_rx - temperature problem

### ISSUE THREAD

**Issue by 9a7aof** [projecthorus/radiosonde_auto_rx#236]
Master version show good temperature, testing version show  -273.
Please, correct this.

Thanks!

**Comment by darksidelemm** [comment]
I pushed a change this morning which should have added support for this back in (1.2.0-beta8). (I forgot to add the --ptu option when starting the m10 decoder)
Run a git pull then restart, and hopefully it will work again. 

Please let me know how you go.

**Comment by 9a7aof** [comment]
Version 1.2.0-beta8 works fine with M10. 
Temperature is OK.
Thanks!
