### ISSUE TITLE
Add RSSI indication to web interface

### ISSUE THREAD

**Issue by mclane** [projecthorus/radiosonde_auto_rx#244]
It would be nice to have a kind of RSSI indication in the upper part of the web interface. I only have a yagi antenna on a tripod which I move manually if I loose contact. With an RSSI indicator I could always check if I need to turn the antenna. Otherwise: great job! I like it!

**Comment by snh** [comment]
Hey @mclane 👋 

The latest release (1.2.0) displays the SNR in the web interface when using the [experimental decoders](https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/test/notes/2019-04-26_fsk_demod.md). These are also logged (if enabled), and included in the UDP broadcast based payload summaries (https://github.com/projecthorus/radiosonde_auto_rx/issues/204#issuecomment-531461695).

If not already enabled, you can enable these by [updating your `station.cfg` configuration file](https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/station.cfg.example#L400-L413).

This can be used to help align your antenna, and to compare the performance of different antenna, filter, and lna combinations.

**Comment by mclane** [comment]
Hi @snh ,
thanks for the hit; that was what I was looking for! So the issue can be closed.
