### ISSUE TITLE
Multiple SDRs - specify functions?

### ISSUE THREAD

**Issue by sm3ulc** [projecthorus/radiosonde_auto_rx#250]
Hello!

Have one rpi with double dongles but totally different antennas. Is it possible to have them both scanning or would that be a feature request?

Thanks for awesome work!

**Comment by darksidelemm** [comment]
At the moment scanning only occurs on a single dongle, and auto_rx is really designed for all SDRs hanging off a single omni-directional antenna.

I have heard of other stations using multiple antennas, but only by using knowledge of what sondes are expected in each direction, and setting blacklists / whitelists appropriately.

**Comment by sm3ulc** [comment]
My solution is to run two instances of autorx, i.e. one per dongle. Seems to work.
