### ISSUE TITLE
Running 4 RTL devices does not (always) work

### ISSUE THREAD

**Issue by zanco** [projecthorus/radiosonde_auto_rx#251]
Hi, running 4 rtl devices (Kerberos in this case) on a Pi4 1 GB does not work failsafe.

> 2019-11-07 18:50:37,689 ERROR:Scanner #003 - RTLSDR #003 non-functional - exiting.
2019-11-07 18:50:39,693 INFO:SDR #003 has been allocated to Scanner.
2019-11-07 18:50:45,178 INFO:RTLSDR - Attempting to reset: /dev/bus/usb/001/005
2019-11-07 18:50:52,702 INFO:RTLSDR - Attempting to reset: /dev/bus/usb/001/005

PD3T did run into the same error some time ago, he is running on a HP desktop but got the same error message.

This could be an USB bus problem instead of a software error of course.

Thanks,
Ben

**Comment by darksidelemm** [comment]
This has been looked at previously, and all I could conclude was it was some kind of USB bus issue or limitation. Three RTLSDRs seems to work fairly reliably, but yes, add on any more and things become unstable.
There's not really anything specific in auto_rx that can fix this, so I'm closing this issue.
