### ISSUE TITLE
fsk_demod

### ISSUE THREAD

**Issue by rs1729** [projecthorus/radiosonde_auto_rx#275]
soft-output of "fsk_demod -s" is < 0 if normal fsk_demod bit-output is 1, and > 0 if bit-output is 0.
https://github.com/projecthorus/radiosonde_auto_rx/blob/master/utils/fsk.c#L968
(log-likelihood-algebra representation?)

EDIT/REMARK:
The --softin option of the *mod-decoders assumes hard_bit = (soft_bit > 0), i.e. the opposite.
Using "fsk_demod -s" output, the decoders would need the option -i.

**Comment by darksidelemm** [comment]
The fsk_demod soft-decision output uses the same convention as log-likelihood ratios, in that a more positive soft-decision value means the bit is more likely to be 0. This is the convention used in LDPC error correction decoding, which is where the soft-decision output was used.

I'll make sure to use the -i option!
