### ISSUE TITLE
Add geo: URI on displayed coordinates

### ISSUE THREAD

**Issue by drid** [projecthorus/radiosonde_auto_rx#300]

**Comment by darksidelemm** [comment]
Did this on chasemapper, so probably not too difficult.

Chasemapper ref: https://github.com/projecthorus/chasemapper/blob/master/static/js/tables.js#L100

**Comment by darksidelemm** [comment]
Resolved in testing branch under this PR: https://github.com/projecthorus/radiosonde_auto_rx/pull/302

Will release after testing on my station.

**Comment by darksidelemm** [comment]
Closed in https://github.com/projecthorus/radiosonde_auto_rx/releases/tag/v1.4.0
