### ISSUE TITLE
Provide dynamic KML

### ISSUE THREAD

**Issue by drid** [projecthorus/radiosonde_auto_rx#303]
Provide kml file with autorefresh that can be use by GoogleEarth or other KML compatible apps

KML file could be something like 
```
           "<?xml version=\"1.0\" encoding=\"UTF-8\"?> \
            <kml xmlns=\"http://earth.google.com/kml/2.1\"> \
                <NetworkLink> \
                    <Link> \
                        <href>" + flask.request.host_url + "rs_feed.kml</href> \
                            <refreshMode>onInterval</refreshMode> \
                            <refreshInterval>10</refreshInterval> \
                    </Link> \
                </NetworkLink> \
            </kml>"
```

and **rs_feed.kml** can have the actual coordinates

**Comment by darksidelemm** [comment]
I actually wrote something like this a looooong time ago, as a bit of a precursor to chasemapper ( https://github.com/projecthorus/chasemapper ) 
The code is here: https://github.com/projecthorus/horus_utils/tree/master/apps/kml_chase

Something like this (though without the predictions... that's getting a bit much to add into this repo) could probably be integrated into auto_rx if desired, and could hang off the backend of the existing web interface easily enough. 

Not sure I have the time to work on this in the short term though, it's a fairly big addition.

**Comment by drid** [comment]
Should i give it a try?

**Comment by darksidelemm** [comment]
Yep, that would be great! Make sure you target the testing branch.

**Comment by drid** [comment]
Still a WIP currently under testing https://github.com/projecthorus/radiosonde_auto_rx/pull/304

**Comment by darksidelemm** [comment]
Closed in https://github.com/projecthorus/radiosonde_auto_rx/releases/tag/v1.4.0
