### ISSUE TITLE
Email Service Testing

### ISSUE THREAD

**Issue by dh47** [projecthorus/radiosonde_auto_rx#306]
Is there a way to make sure the email settings are correct without having to wait for a launch?

**Comment by darksidelemm** [comment]
Yes! 

From the radiosonde_auto_rx/auto_rx directory, run:
python -m autorx.email_notification

If you have your email settings correct, it should send you a notification email for a dummy launch.

I should probably add this to the wiki...

**Comment by dh47** [comment]
Wow, that works very well!  Just  fixed the issue before the launch!

**Comment by darksidelemm** [comment]
Good to hear! I'll add a note in the wiki somewhere...
