### ISSUE TITLE
dependencies - missing a package

### ISSUE THREAD

**Issue by agent-cooper** [projecthorus/radiosonde_auto_rx#315]
add 'libtools' to the list of packages to be installed on raspberry pi

**Comment by darksidelemm** [comment]
This isn't brought in as a dependency of any of the other packages? 
At what point does not having this package break the installation steps?

**Comment by agent-cooper** [comment]
I was just installing on an RPi 3 with the latest Raspbian, and I got an error message saying that it was looking for libtoolize which is in the libtool package

**Comment by darksidelemm** [comment]
Yes, but at which stage was this? During build of the rtl-sdr libraries, or somewhere else?

**Comment by agent-cooper** [comment]
After entering: sudo apt-get install rtl-sdr

**Comment by darksidelemm** [comment]
OK, that's extremely odd, since there should be no building going on at that point. No harm in adding libtool to the package list to be installed, but I haven't had any other reports of this being an issue.
