### ISSUE TITLE
Configuration parsing needs to be done better

### ISSUE THREAD

**Issue by TheSkorm** [projecthorus/radiosonde_auto_rx#36]
Every time we add a config variable we break backwards compatibility with users.

We should probably use the configparser library to have a sensible default file and then read in the users config.

We should also configure a command line arg to read in another config file

**Comment by SloMusti** [comment]
Command line choice of config file has been implemented in 716af84b685cf423e8cd3b0dbd95abe9db17407d

**Comment by TheSkorm** [comment]
I'm going to close this for the moment. Better options are available but would likely increase dependencies and isn't worth the effort.
