### ISSUE TITLE
Fails to exit on timeout.

### ISSUE THREAD

**Issue by ED6E0F17** [projecthorus/radiosonde_auto_rx#37]
https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/auto_rx.py#L973

seems to need an extra "OZI_PUSH_RUNNING = False" to close a thread on exit, When not running continuously you can get some nice stats appended to the flight log. Thanks.

**Comment by darksidelemm** [comment]
Fixed in https://github.com/projecthorus/radiosonde_auto_rx/commit/ea7a27af39ee5cb067362b8bb6269978b2d8ffcb

Thanks!  Come join #highaltitude on Freenode IRC at some point, we'd love to find out who else is running this software!
