### ISSUE TITLE
Tracking radiosonde

### ISSUE THREAD

**Issue by Piter-NS** [projecthorus/radiosonde_auto_rx#387]
A proposal to expand the ability to track received radiosonde on the map.

If we receive more than one radiosonde, it would be good to be able to choose which sonde to track on the map, e.g. by clicking the sonde icon or selecting it from the table with the received data.

**Comment by darksidelemm** [comment]
To be honest the auto_rx web GUI was not really intended for this kind of
use. It was always intended just as a status indication that the station is
receiving properly.

Other interfaces like tracker.sondehub.org are far better suited for
long-duration tracking of a sonde, running predictions, etc. If chasing,
then chasemapper is better suited. I know of many users that leave
chasemapper running continuously for at-home tracking as well (though it
really wasn't designed for that).
