### ISSUE TITLE
Radius cap is not skipping to next sonde

### ISSUE THREAD

**Issue by pit711** [projecthorus/radiosonde_auto_rx#399]
would be nice when radius cap is breached auto_rx will skip to the next sonde.

still no skipping implemented, :sadface:

![image](https://user-images.githubusercontent.com/40324107/109803245-1c919500-7c21-11eb-91c4-db46994a42d7.png)

**Comment by darksidelemm** [comment]
You may have missed this option: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/station.cfg.example#L483

If this is set, auto_rx will block the frequency of the offending sonde for a few hours.

**Comment by darksidelemm** [comment]
@pit711 is the above option doing what you wanted?
