### ISSUE TITLE
Enhancement Request: Specify APRS server

### ISSUE THREAD

**Issue by vk4tec** [projecthorus/radiosonde_auto_rx#40]
I would like to be able to direct the APRS data towards a defined server.

Either rotate.aprs.net or say UI_VIEW ( 192.168.1.14 )

This is to allow access and to APRS stream being sent. 

This is believe is hard coded and round robins.

Andrew

**Comment by darksidelemm** [comment]
Simple enough, just requires an added entry in the config file, and code to parse it in.
The current default server is rotate.aprs2.net, which I figured was a good option. 

Will take a look on the weekend.

**Comment by darksidelemm** [comment]
Resolved in https://github.com/projecthorus/radiosonde_auto_rx/commit/9f4fcb0149dd75bc5fdc80f32d5272652c10bf5d
