### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Piter-NS** [projecthorus/radiosonde_auto_rx#426]
After installing version 1.5.1 Beta 1, when decoding data from the probe, the following message appears:

> 2021-04-02 13: 33: 18,156 ERROR: Decoder # 00000022 RS41 400.600 - Failed to run telemetry filter - 'module' object has no attribute 'timezone'

What could be causing this?

**Comment by darksidelemm** [comment]
Which version of Python are you running? If you're still on Python 2.7, things are going to start to break badly from now on.

**Comment by darksidelemm** [comment]
This looks very much like a python version issue... so closing this. let me know if this is still an issue.
