### ISSUE TITLE
Replay from wav file

### ISSUE THREAD

**Issue by vk4tec** [projecthorus/radiosonde_auto_rx#43]
I am not sure how this is achievable.

I would like to make a recording in SDR# in WAV format and then be able to pick that file up my the radiosonde_auto_rx processing scripts.

The idea being that you could go to a hill and record a great pass in wav and then come home and replay or use for demos at radio clubs.

You would have to be sure that you are not connected to the net to allow false packets to pass.

This enhancement would be handy for testing new features and additions, not withstanding having a live radio sonde or a test radio sonde. 

I am not sure if the GPS will not work as it is not real time with respect to the empheris data 

Andrew VK4TEC

**Comment by darksidelemm** [comment]
This one is very difficult to do with the current software architecture. Once we do the re-structure to a python module (a few months away), it might become easier.
GPS will always be an issue with the RS92s - you need the ephemeris data for the time of the recording. With the RS41s this won't be a problem.

You can play a wave file back through the demodulator manually:
https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/auto_rx.py#L470
but there is no way of handling the output at the moment. 

Give it a few months and then we'll revisit it.

For now, for testing we use collected radiosondes, or just wait for the next launch.
