### ISSUE TITLE
ASCII ART frequency scan

### ISSUE THREAD

**Issue by vk4tec** [projecthorus/radiosonde_auto_rx#44]
Is it possible to show in ascii art something like this to show the results of the freq scan ?

400.05 ** ( 36 )
401.00 ** ( 36 )
401.05 ********************** ( 78 ) 
402.00 ** ( 37 )

Giving a sort of pseudo spectrum analyser 

Andrew Rich VK4TEC

**Comment by darksidelemm** [comment]
Yes, but I don't see the need for this application. This code is meant to be run headless, without user intervention. Also, there's a *lot* of data points, which will be difficult to display meaningfully in the confines of a terminal window.

If you want to look at the output of rtl_power (which is written out to log_power.csv on each scan), there are plenty of tools out there to do that. 
We also already have a script in utils to plot the output: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/utils/plot_rtl_power.py
