### ISSUE TITLE
Station position for _radius_breach not updating from GPSD

### ISSUE THREAD

**Issue by g7gpr** [projecthorus/radiosonde_auto_rx#443]
The _radius_breach only seems to work from the station position set in the config file, not from data received from GPSD. I'll do some more testing to confirm.

**Comment by darksidelemm** [comment]
I'm not that surprised if this is the case.

The radius check is done here: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/auto_rx.py#L508

An update to the global config dictionary probably needs to be added into this function:
https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/auto_rx.py#L609

That should fix it...
