### ISSUE TITLE
Create kml from sonde log files

### ISSUE THREAD

**Issue by vk4tec** [projecthorus/radiosonde_auto_rx#45]
Creating` kml files from /log/\*RS\*

Outputs to /var/www/html/radiosondes.kml 

( you can pick this up from google earth with a refresh )

Please see Andrew for latest "sonde_to_kml.pl"

A

**Comment by darksidelemm** [comment]
I've written a python log-to-kml utility, based on code I already had from another project. This has been added in https://github.com/projecthorus/radiosonde_auto_rx/commit/5cadfc9ba459e5fbd1e03c215aa853d86d6961d3

Documentation is here: https://github.com/projecthorus/radiosonde_auto_rx/wiki/Log-Files

It uses the fastkml and shapely libraries, as I didn't see the point implementing my own KML file generator when there were already good libraries available.
