### ISSUE TITLE
Adding an LED to the Pi3 to indicate RX

### ISSUE THREAD

**Issue by vk4tec** [projecthorus/radiosonde_auto_rx#47]
Without a screen it is quite hard to guage when a Radio Sonde lock has happened.

When i was working on a GPS/GLONASS tracker I found it handy to have a couple of LED's on the GPIO

I would like to add this functionality to indacate a SONDE LOCK

A Blue LED might be used to indicate RadioSone lock. 

Here is the code I used to the GPS logger.

This is "flash LED" code but there is no reason why the GPIO cant be turned ON and OFF with RX

If unused, this should have no affect on people not using the GPIO indicator.

It would all value and make the project more attractive

#!/usr/bin/python
import RPi.GPIO as GPIO ## Import GPIO library
import time
GPIO.setmode(GPIO.BOARD) ## Use board pin numbering
GPIO.setup(7, GPIO.OUT) ## Setup GPIO Pin 7 to OUT
GPIO.output(7,True) ## Turn on GPIO pin 7
time.sleep(1)
GPIO.output(7,False);

**Comment by darksidelemm** [comment]
I don't want to tie this repository down to any particular hardware. 

The code already has *more* than enough ways of outputting data, you can go write your own script to use one of those and enable your LED. The config file is cluttered enough as it is!

The output that would probably be easiest to use is using the 'payload summary' output:
https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/station.cfg.example#L140

That emits payload position data via UDP broadcast. These can be read using the [UDPListener](https://github.com/projecthorus/horus_utils/blob/master/horuslib/listener.py#L15) class, located within the [horus_utils](https://github.com/projecthorus/horus_utils/wiki) repository. In my car I have a little 4-character shield for a Pi Zero which displays the current payload altitude, using data gathered via this 'payload summary' message. The code that runs that is here:
https://github.com/projecthorus/horus_utils/blob/master/apps/other/fourletterhud.py

It should be easy enough to write something similar (either using the UDPListener class, or writing your own) to listen for the UDP packets, and enable an LED based on their content (or really, their presence).
