### ISSUE TITLE
Problems with new receiving sonde

### ISSUE THREAD

**Issue by Piter-NS** [projecthorus/radiosonde_auto_rx#470]
Hi, when my receiver starts to decode the signal from the new probe, only the path is shown on the map. Only after refreshing the page, the balloon or parachute symbol is displayed.

<img width="787" alt="Zrzut ekranu 2021-04-30 o 14 25 46" src="https://user-images.githubusercontent.com/54403168/116725481-3c0b2b00-a9e2-11eb-80ef-623addf9674e.png">

**Comment by LukePrior** [comment]
Yeah I seem to be encountering the same problem are you on the beta version?

**Comment by darksidelemm** [comment]
Found the bug, fixed on the testing branch. Will close this issue since it doesn't affect the main branch.
