### ISSUE TITLE
Station Log

### ISSUE THREAD

**Issue by vk4tec** [projecthorus/radiosonde_auto_rx#49]
I can see an advantage in keeping a simple station log

On acquisition or sonde , "Detected Sonde type xx "

Append to a station.log

date,time,type,id,freq
date,time,type,id,freq
date,time,type,id,freq
date,time,type,id,freq

Perhaps on "sonde lock" an entry could be added

This would assist in presenting a simple running log of sondes received for house keeping

Andrew

**Comment by darksidelemm** [comment]
This information is already available... it's the list of per-sonde log files:

```
darkside@sonderx:~/radiosonde_auto_rx/auto_rx/log $ ls *_sonde.log
20180217-111814_M4543361_RS92_401520_sonde.log
20180217-231905_M4543015_RS92_401490_sonde.log
20180218-011613_M4534273_RS92_402020_sonde.log
20180218-111711_M4543014_RS92_401500_sonde.log
```
I don't see the need for yet another log file showing the same thing.
