### ISSUE TITLE
Feature Request:  Place callsign in window title for web client.

### ISSUE THREAD

**Issue by Moll1989** [projecthorus/radiosonde_auto_rx#535]
A few of us log in to multiple stations, sometimes simultaneously.

It would be good if the page title showed the station callsign so that we can see which tab is which in our browser, rather than all titles being "Radiosonde Auto-RX Status".  For Example something like "VK5CBM_AUTO_RX Status" would make it easy to differentiate tabs.

It looks like this could fairly simply be included in the index.html template?

**Comment by darksidelemm** [comment]
This should be fairly trivial to do...

**Comment by darksidelemm** [comment]
Added this in the testing branch.

**Comment by F1TKE** [comment]
Nice 
![image](https://user-images.githubusercontent.com/81046764/124487733-5b8e4d80-ddaf-11eb-87f0-49d042ff4d22.png)

**Comment by darksidelemm** [comment]
Currently it's using both the sondehub and APRS callsigns ( SONDEHUB / APRS ) but I might wind that back to just use the Sondehub callsign...
