### ISSUE TITLE
Strange polygon on coverage map

### ISSUE THREAD

**Issue by g7gpr** [projecthorus/radiosonde_auto_rx#536]
![image](https://user-images.githubusercontent.com/77130399/124407390-5e208100-dd76-11eb-9091-7db3582b4c79.png)

**Comment by darksidelemm** [comment]
That is a bit odd, and is probably an artefact of not having enough datapoints.

If you could zip up your log directory and post that somewhere, that would help figure out what's going on.

**Comment by g7gpr** [comment]
[log.tar.gz](https://github.com/projecthorus/radiosonde_auto_rx/files/6762913/log.tar.gz)

Log directory attached. Great new features.

**Comment by LukePrior** [comment]
> That is a bit odd, and is probably an artefact of not having enough datapoints.

Yeah it's exactly that not much can really be done with the existing code to fix it, would need some complex algorithm or something

**Comment by darksidelemm** [comment]
Actually something that might be a simple change is to insert the station position when there is no data for a particular azimuth. That would probably clean up the example above.

**Comment by g7gpr** [comment]
I'm sure you are already across this, but S3551090 is the sonde that causes the issue. This was a rare reception of a sonde from Geraldton, rather than Perth. Once I rename that file the polygon is normal.

**Comment by darksidelemm** [comment]
This should be fixed in 1.5.5

**Comment by g7gpr** [comment]
![image](https://user-images.githubusercontent.com/77130399/129478746-1e648e8c-210d-428f-9789-cf88a3f161a7.png)

I believe it is. I will test again tomorrow with the log directory above.

**Comment by g7gpr** [comment]
![image](https://user-images.githubusercontent.com/77130399/131771161-8e1cba72-c43d-4c76-b442-2f6e1e0d1665.png)

I untarred log.tar.gz file from the example, and reran the coverage - looks perfect now.
