### ISSUE TITLE
Offline maps?

### ISSUE THREAD

**Issue by UlianTvinov** [projecthorus/radiosonde_auto_rx#568]
Hello. Can you please, answer my question. I think about offline maps at Auto-RX 1.5.5? If it posible, how i can manage this? I want try put map's into my raspberry pi, and use it like mobile point. Ofline-maps needed because mobile internet connection not stable here... Thanks!

**Comment by darksidelemm** [comment]
As this is already built into chasemapper (and chasemapper was designed for offline balloon chasing), I have no intend to add offline mapping support to auto_rx.
Chasemapper is available here: https://github.com/projecthorus/chasemapper
