### ISSUE TITLE
Feature request: Sidescroll in telem_table

### ISSUE THREAD

**Issue by Moll1989** [projecthorus/radiosonde_auto_rx#576]
Sometimes I have more fields showing on the telemetry table than properly fit on my screen.  

It appears there is no way to side-scroll through the table, so I keep shrinking columns to see info such as SNR (its quicker and easier than opening settings and hiding columns).  It would be really cool if we could sidescroll this table, perhaps even with click and drag for a consistent UI feel with the leaflet map?

**Comment by darksidelemm** [comment]
Just a note on this - it is possible to side-scroll on this table right now... but it depends on what kind of input methods you have available. Here on my Mac I can scroll left/right on the table by two-finger swiping left-right.
