### ISSUE TITLE
M10 GTOP radiosondes packets seem to be wrongfully filtered out because of their GPS satellites number

### ISSUE THREAD

**Issue by F4HVO** [projecthorus/radiosonde_auto_rx#578]
Hi, I use radiosonde_auto_rx to track reprogrammed M10 radiosondes that appear as Gtop M10 (`t_M10plus` as second word is 0xAF). 
For these sondes, the decoded number of visible satellites seems to be random (and is often 0).
In `m10mod.c` it appears that `gpx->numSV` is only set for `t_M10` radiosondes (in function `get_GPSweek`), however, it is always read to produce the field `sats` of the json output.

If I am not missing something, the `gpx->numSV` value that gets in the json output and then is used by the web app telemetry filter is not relevant for `t_M10plus` radiosondes.

If this issue is confirmed I can work on a patch.

**Comment by rs1729** [comment]
@F4HVO thanks, numSV is only read for Trimble-M10, thus json sats output should be only for Trimble-M10.
I changed it.

**Comment by F4HVO** [comment]
Sorry for the delay but I just tested and its okay ! No more invalid number of visible sats.
Thank you very much.
