### ISSUE TITLE
Аудио контроль эфира

### ISSUE THREAD

**Issue by BatiaMahno** [projecthorus/radiosonde_auto_rx#597]
Already several times there was a problem, there is no sound control. There is a powerful signal, the decoder does not respond, you need to make sure that this is by quickly listening to the broadcast, it can be a new type of probe or just a hindrance. Can I add audio controls?

**Comment by darksidelemm** [comment]
Sadly this is not really practical with the current demodulation chain, which uses IQ data, and is not something I am planning on adding support for, sorry.
