### ISSUE TITLE
getting error and restarting device

### ISSUE THREAD

**Issue by weather-tracker** [projecthorus/radiosonde_auto_rx#598]
i tried it and all it did was say error restarting device.
the webpage showed no signals or noise.
but the rtl-sdr does work i tried it with gqrx and it worked, listened to radio stations.

**Comment by TheSkorm** [comment]
Can you provide the logs? How have you installed it, via docker or native?

```
#native
sudo journalctl -u auto_rx.service -f -n
#docker
docker logs --tail 500 radiosonde_auto_rx
```
