### ISSUE TITLE
Computer Sound Card Instead of SDR

### ISSUE THREAD

**Issue by Frojoe6969** [projecthorus/radiosonde_auto_rx#607]
Hello,

I started doing all the research and seems I have everything set up properly in terms of radio, antenna, hearing the packets from the weather balloon, Auto-RX set up on a virtual Linux machine… The one issue I am having is getting the sound to go to auto RX from the microphone jack instead of using an SDR. 

What am I missing?  When I try to run $ Python3 auto_rx.py I get an error message “No Working SDRs! Cannot Run”
 
I would assume you could connect the output a UHF radio connected to my computer microphone jack and auto_rx would be able to see the audio to decode. Is that not the case? Am I restricted to using and SDR?

**Comment by darksidelemm** [comment]
Yes, this software is SDR only. It is intended to be fully automated.

**Comment by TheSkorm** [comment]
You might want to consider using this sdr++ plugin https://github.com/dbdexter-dev/sdrpp_radiosonde or sondemonitor
