### ISSUE TITLE
Scan plot height in web interface

### ISSUE THREAD

**Issue by pavolgaj** [projecthorus/radiosonde_auto_rx#608]
How to change the height of the scan plot (make it smaller) in the web interface? If I have opened scan plot, the map is very small - I couldn't see anything on it.
I tried to look in CSS files but I didn't find anything...

**Comment by TheSkorm** [comment]
![image](https://user-images.githubusercontent.com/234867/152422064-40f2c5c9-1ac0-4312-bc41-df83205ee442.png)
![image](https://user-images.githubusercontent.com/234867/152422103-689a2302-9e0e-4b04-8593-88b0fedc949a.png)
![image](https://user-images.githubusercontent.com/234867/152422130-4d494d26-55cd-44a6-b061-4647dd930e55.png)

You can use the settings to hide the scan plot entirely and make the map full screen

**Comment by pavolgaj** [comment]
Yes, I know about this option. I want to show scan plot but smaller.
