### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by pavolgaj** [projecthorus/radiosonde_auto_rx#614]
If someone has raw hex data from today sondes T1540520, T1240374 or S2911549, send it me, please, to "palko15 (at) post (dot) sk". Thanks!

**Comment by darksidelemm** [comment]
This is not the place for these kind of requests. The mailing list is the right place for that.

Why in particular are you looking for hex data? Note that by default auto_rx does not save raw hex data, and i highly doubt many stations have that enabled.
