### ISSUE TITLE
simple questuin regarding testmails

### ISSUE THREAD

**Issue by edegraaff** [projecthorus/radiosonde_auto_rx#629]
hi, i build up the sondetracker on a raspbian light. 
Is it possible to test the mail script? It could be some email specific components are lacking, or something wend wrong during sending the email. I want to debug here and fix the issue not reveiving the mail alerts.

thanks

eelco

**Comment by TheSkorm** [comment]
You can test the mail with these instructions : https://github.com/projecthorus/radiosonde_auto_rx/wiki/Configuration-Settings#e-mail-notifications
