### ISSUE TITLE
32 bit vs 64 bit Raspberry Pi OS?

### ISSUE THREAD

**Issue by bismurphy** [projecthorus/radiosonde_auto_rx#633]
Hi,

Given that the setup requirements indicate that a dedicated single-board computer (such as a Raspberry Pi 3 or better) is ideal, and given that there are now both 32 bit and 64 bit operating system images, I think it would be useful if the guides could also mention whether there is a preferred operating system version. Can radiosonde_auto_rx benefit from native 64-bit operation, or are all of its operations equally good on either OS?

I'm not just asking for myself here, to be clear, I'm suggesting that this also be added to docs to ensure that operators are using the best version available for their systems.

Thanks!

**Comment by darksidelemm** [comment]
There isn't really a preferred option. auto_rx will work on either 32-bit or 64-bit. There may be a slight performance advantage on 64-bit, but unless you're planning on running a lot of other computationally intensive processes on the same RPi (not really recommended) then it doesn't really matter.
