### ISSUE TITLE
Error determining version

### ISSUE THREAD

**Issue by rgf123** [projecthorus/radiosonde_auto_rx#634]
Hi,
From latest update to 1.5.10 I get this error message in log:

ERROR:Version - Error determining version from URL https://raw.githubusercontent.com/projecthorus/radiosonde_auto_rx/master/auto_rx/autorx/__init__.py: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=5)

ERROR:Version - Could not determine latest versions.

Is this something could I fix?

Thanks.

**Comment by darksidelemm** [comment]
Given that URL ( https://raw.githubusercontent.com/projecthorus/radiosonde_auto_rx/master/auto_rx/autorx/__init__.py ) is working, this suggests a connection issue from where you are running auto_rx to github.

auto_rx should continue to run OK, It just won't be able to display if there's any newer versions available.

**Comment by rgf123** [comment]
It runs OK even with that error, you are right.
Running in raspberry CLI:
wget https://raw.githubusercontent.com/projecthorus/radiosonde_auto_rx/master/auto_rx/autorx/__init__.py

--2022-05-12 00:24:44--  https://raw.githubusercontent.com/projecthorus/radiosonde_auto_rx/master/auto_rx/autorx/__init__.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response...

So, it connects but can't find the file?

**Comment by darksidelemm** [comment]
In the case of your error from auto_rx, the request is timing out: 
```
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=5)
```

**Comment by rgf123** [comment]
Yes, so both are failing:
- auto_rx internal process times out
- requesting the file from cli, it also fails (it was 'awaiting response....' minutes), the timeout was a CTRL+C

I think it is related to availability of the server. I have tested several times from CLI and I got the file once from many attempts.

**Comment by darksidelemm** [comment]
Yep. In which case there's not a whole lot I can do about this one, sorry!

**Comment by rgf123** [comment]
You are right.
Could I configure logging to only show INFO messages?

**Comment by darksidelemm** [comment]
No - inhibiting errors like this is generally is a bad idea. It should only appear once on startup anyway...

**Comment by rgf123** [comment]
Understood.
Thanks.
