### ISSUE TITLE
Radiosonde auto rx on Windows 

### ISSUE THREAD

**Issue by GianlucaB2000** [projecthorus/radiosonde_auto_rx#636]
Hi everyone, it is possible to run Radiosonde auto rx on Windows, without having to use virtual machines (like Horus gui, but for "normal" radiosondes) in order to send the telemetry to Sondehub? For me it would be convenient to be able to use the function of landing forecast.

**Comment by darksidelemm** [comment]
There is no intention of supporting radiosonde auto_rx on Windows. There are numerous issues with USB devices which is not something I have the time or inclination to deal with. Sorry...
