### ISSUE TITLE
IMET4-RSB Possible Issues

### ISSUE THREAD

**Issue by RavenV-tiff** [projecthorus/radiosonde_auto_rx#643]
Hi,
I have a problem with auto_rx when trying to pickup iMet-4RSB sondes. The sondes are being detected but the decoder always times out. I do not have this issue with other sonde types. My hardware is the Nesdr smart SDR dongle with a yagi antenna. I have attached a screen shot of the output of the program.
![Screenshot from 2022-07-11 15-03-13](https://user-images.githubusercontent.com/60206946/178811345-d5e1f997-6f18-4dfb-a68c-8faa05fe45f5.png)
While the screenshot shows version 1.5.9 being ran, I have tested with the latest 1.5.10 version with the same results. I don't know if this is a different variant of imet-4 from which auto_rx can decipher.

**Comment by RavenV-tiff** [comment]
It may be some time before I get the next opportunity to check the program. Our field study ended, but we do still have some RSBs remaining. So next time we send a payload up I'll try recording audio and provide the output with -v.

**Comment by darksidelemm** [comment]
Ahh damn. If you could turn one on on the ground and get a recording that would be really useful!

**Comment by darksidelemm** [comment]
Any updates on this? A recording of an iMET4-RSB, in particular with a XDATA payload attached would be handy.

**Comment by RavenV-tiff** [comment]
Unfortunately we haven't had any deployments since I last posted. I will discuss with my lab coordinator about opening up a sonde to capture the radio signals with XDATA from an ozonesonde we recovered. They may say not to until next deployment, which I really cannot so for sure when that will be.

**Comment by RavenV-tiff** [comment]
@darksidelemm I received permission to open an iMET4-RSB. I will attach an ECC ozonesonde to it, so it will have valid XDATA. In terms of audio recording how would you like me to do it? I can simply record the computer audio with something like Audacity and send you the wave file with the decoded data. Would this work? How long of a sample would you need?

**Comment by darksidelemm** [comment]
Maybe a minute should be fine. FM-demodulated audio (like you would use with the iMet software) is all we need for this.
