### ISSUE TITLE
Why is velocity not in m/s

### ISSUE THREAD

**Issue by Joanvoo** [projecthorus/radiosonde_auto_rx#648]
Radiosonde Auto-RX 1.6.0-beta3 webinterface

Hi,
Why is velocity not in m/s  just as in sondehub
ascent rate is in m/s 
calculate is easier when the sonde is on the ground..

73 Joan

**Comment by darksidelemm** [comment]
Are you talking about horizontal velocity? This is in kph, with an option for miles/hr (a request from our American friends...)

Maybe having the horizontal velocity being in m/s could be added as an option...

**Comment by Joanvoo** [comment]
Yes I mean horizontal velocity.
in sondehub its also a option.
it would be nice if there was an option in the webinterface



Op za 30 jul. 2022 om 12:44 schreef Mark Jessop ***@***.***>:
