### ISSUE TITLE
Radiosonde Auto-RX 1.6.0-beta13 graphical request 

### ISSUE THREAD

**Issue by zanco** [projecthorus/radiosonde_auto_rx#693]
Hi,
Can I (we) have different colours for the balloons on the map  which are actively received ?

![image](https://user-images.githubusercontent.com/4477734/198878242-b1569f56-f177-4160-b830-cf1e16b06b42.png)
With some stations doing multiple launches in 2 hours time slot it's sometimes difficult to locate the active flights on the auto_rx map.

Thanks,
Ben

**Comment by darksidelemm** [comment]
How about having the green lines only appear if the telemetry is less than X seconds old (say, 10 seconds)?

**Comment by zanco** [comment]
Sounds like a good solution !

**Comment by darksidelemm** [comment]
I've implemented this in this PR: https://github.com/projecthorus/radiosonde_auto_rx/pull/702
Wait for the docker build to finish and it will be live on testing :-)
