### ISSUE TITLE
Expand multiple sdr wiki

### ISSUE THREAD

**Issue by duk3luk3** [projecthorus/radiosonde_auto_rx#695]
Wiki: https://github.com/projecthorus/radiosonde_auto_rx/wiki/Configuration-Settings#use-of-multiple-rtlsdrs

Suggested changes:

- Change serial example to a non-numeric string e.g. `N0000002` to document that serial numbers can be non-numeric and avoid the mentioned issues with rtl_ commands interpreting numeric serial numbers as device index
- Add a note that rtl_ commands accept serial numbers for the `-d` parameter as this is not obvious and not documented in manpages

**Comment by darksidelemm** [comment]
Have fixed the first point. Not sure where in particular you want me to mention the use of -d
