### ISSUE TITLE
meisei_experimental=True makes good result at testing branch

### ISSUE THREAD

**Issue by AstroTaka** [projecthorus/radiosonde_auto_rx#707]
I checked a difference between meisei_experimental=True and False at the same time.

I made a checking environment as following.

ANT:COMET SB-15 + 403MHz BPF + SPLITTER: Mini-Circuits ZESC-2-11 + RTL-SDR v3 x 2

https://static.dxengineering.com/global/images/instructions/cma-sbb-15.pdf
https://www.aliexpress.com/item/1005003670284670.html

I connect two RTL-SDR dongle to one Ubuntu PC and I made two copy of testing branch.
I changed the both station.cfg

test1 station.cfg -> meisei_experimental = False

```
sdr_quantity=1
device_idx = 00000003
web_port = 5001
meisei_experimental = False

```
test2 station.cfg -> meisei_experimental = True

```
sdr_quantity=1
device_idx = 00000002
web_port = 5002
meisei_experimental = True

```
I received one signal of MEISEI IMS-100
The result is...

IMS-100 decode count
meisei_experimental
True : 814
False: 457

meisei_experimental=True start to decode earlier and stop to decode later from meisei_experimental=False.
And meisei_experimental=True can much decode.

I upload a several log file.

meisei_experimental=True
https://drive.google.com/drive/folders/1ehzwStxP-PXzLgDwMcv1Q4H3_Tbm4RRP?usp=share_link

meisei_experimental=False
https://drive.google.com/drive/folders/1Qs0DXLkmg0iMqGe8NiRXtUTrK0H7v_Z0?usp=share_link

It is for your reference.

**Comment by darksidelemm** [comment]
OK, good information. I guess I will set that variable to True in the example config and defaults on the testing branch.
