### ISSUE TITLE
No log display at WebUI in testing branch

### ISSUE THREAD

**Issue by AstroTaka** [projecthorus/radiosonde_auto_rx#708]
I tried to see log data in WebUI.
But I cannot see anything.

I uploaded a screen capture.
https://drive.google.com/file/d/1rei2aA4S6KUefRQwWiuRx99Ab8wdqHL2/view?usp=share_link

What should I to do?

**Comment by darksidelemm** [comment]
OK. have merged a fix for this one.

**Comment by AstroTaka** [comment]
Wow! thanks!
Have you already merged into beta19?
I cannot see a log in WebUI of beta19.

**Comment by darksidelemm** [comment]
I merged this in a bit after I did that, you might need to update again.

**Comment by AstroTaka** [comment]
Now, I can see the log!
Thanks.
