### ISSUE TITLE
Do you have a plan to add "Max Height" in Sonde List?

### ISSUE THREAD

**Issue by AstroTaka** [projecthorus/radiosonde_auto_rx#717]
Currently, "Last H" exist in Sonde List.
And max range and last range also.
Usually case, Max R almost equal Last R.
But Last H is not same as Max H when the sonde is bursted.
I would like to sort max height.

Thanks!

**Comment by darksidelemm** [comment]
No, I don't have intentions to add this. It's already getting too big as it is... 

From the point of evaluating if a sonde is recoverable, last height is more useful.

**Comment by AstroTaka** [comment]
I see thanks!
