### ISSUE TITLE
Sonde List menu keep disabled when push "Plot Paths" twice

### ISSUE THREAD

**Issue by AstroTaka** [projecthorus/radiosonde_auto_rx#719]
I choose one or several sonde.
Push Plot Paths and menu is disabled and enabled.
And push Plot Paths again and menu is disabled.
And then it keep disabled.

I checked showSondeMap of historical.html.
At 1st time, enableMenu() is called in showSondeMap.
But 2nd time, `if (!shown.includes(selectedrows[i]['serial'])) {`is failed. 
and enableMenu() is NOT called in showSondeMap.
When I add a else part for calling enableMenu(), the menu is enabled again at 2nd time also.

**Comment by darksidelemm** [comment]
I see the issue. Have added that line into the testing branch.
