### ISSUE TITLE
Wish / Nice to have : Sonde Frequency in Historical

### ISSUE THREAD

**Issue by zanco** [projecthorus/radiosonde_auto_rx#729]
Hi, is it possible to add the sonde frequency in the Sonde List which appears when you view Historical Data ?

Sometimes I see a sonde on the waterfall, know the frequency but I cannot sort the Sonde List on frequency.

Thanks,
Ben

**Comment by darksidelemm** [comment]
We're kind of running out of width in that list! What would be better is to have some settings to allow what fields are displayed, like on the main page. This is a lot more work though.

**Comment by darksidelemm** [comment]
Resolved in 1.6.1
