### ISSUE TITLE
Scan plot on the last version 1.6.1

### ISSUE THREAD

**Issue by TREBOR81400** [projecthorus/radiosonde_auto_rx#766]
the reception signal does not appear when you activate the Scan Plot

**Comment by darksidelemm** [comment]
Explain this a bit more please. Does nothing appear at all, even with the page left open for a while? 
If your station is already decoding a radiosonde, then there may be no scan plot data to show.

**Comment by TREBOR81400** [comment]
![F80657](https://user-images.githubusercontent.com/109390476/229315927-c0cce94c-d649-4730-a251-af232e414763.png)

**Comment by TREBOR81400** [comment]
![F80657](https://user-images.githubusercontent.com/109390476/229315991-337cabee-2c97-4295-916c-857b59bcc675.png)

**Comment by darksidelemm** [comment]
A few things to check:
- Add /get_scan_data to the end of your URL and see if you get anything (If you do, there will be a *lot* of data, so don't paste it here please)
- Open Developer Tools and look in the console for any errors.

**Comment by ly5p** [comment]
the problem is with chrome browser
![scanplot](https://user-images.githubusercontent.com/123068477/229334387-f1d82536-98e0-4842-99a5-df267af72d51.png)
![scanplot_data](https://user-images.githubusercontent.com/123068477/229334390-ffdf9d2f-4813-47ea-a100-4a188d551151.png)

**Comment by darksidelemm** [comment]
Is it? I've got scan plots working fine on Chrome on both OSX and Windows.

**Comment by TREBOR81400** [comment]
Hello, thank you for your help and advice, the situation is back to normal.
