### ISSUE TITLE
Radiosonde_auto_rx 1.6.1 update

### ISSUE THREAD

**Issue by Mopar44084** [projecthorus/radiosonde_auto_rx#769]
There seems to be missing columns in the history after the 1.6.1 update. It seems to be missing distance, and packets received etc.
![Screenshot_20230507-135702-547](https://user-images.githubusercontent.com/86167080/236700027-1fe7702f-7488-427c-bd6a-f257a08badcd.png)

**Comment by darksidelemm** [comment]
Click the configuration button at the top right of the historical view page. you should be able to select what columns you want from there.

**Comment by Mopar44084** [comment]
Thanks, that fixed it! How do you log in into controls?

**Comment by darksidelemm** [comment]
Not sure what you mean by 'log in' in this case?

**Comment by Mopar44084** [comment]
its under settings and then Controls, it asks for a password

**Comment by darksidelemm** [comment]
Ahh, this is the 'web control' stuff. Refer here: https://github.com/projecthorus/radiosonde_auto_rx/wiki/Web-Interface-Guide#advanced-controls

Going to close this issue now
