### ISSUE TITLE
dont see spectra while RTLSDR scanning 

### ISSUE THREAD

**Issue by laarhoven1** [projecthorus/radiosonde_auto_rx#771]
spectra peaks not visible on scanpot

**Comment by laarhoven1** [comment]
Problem found its not showing in firefox but with google crome its ok

**Comment by darksidelemm** [comment]
Can you please look in your browser console for any errors?

**Comment by darksidelemm** [comment]
Also, a screenshot showing the issue (perhaps the same scan plot shown on both firefox and chrome) would be handy...

**Comment by darksidelemm** [comment]
This is what I see on Firefox on my machine. Appears to be working here :-/

<img width="1074" alt="Screen Shot 2023-05-14 at 09 16 46" src="https://github.com/projecthorus/radiosonde_auto_rx/assets/1040275/8dab534d-5697-424b-9fc9-09cfebdbab6f">

**Comment by laarhoven1** [comment]
![Screenshot_2](https://github.com/projecthorus/radiosonde_auto_rx/assets/93873923/9d991e37-8af9-40b6-b0c4-b0dbbc2c15b6)
![Screenshot_1](https://github.com/projecthorus/radiosonde_auto_rx/assets/93873923/266b0261-4cef-4640-82c1-3f6a69b52e2a)
First a had this issue after rechecking with firefox today the problem seems to be solved
