### ISSUE TITLE
USA Radiosonde in use: DFM-17

### ISSUE THREAD

**Issue by chris451gh** [projecthorus/radiosonde_auto_rx#788]
The US national weather service is now using the DFM-17
https://www.sigidwiki.com/wiki/Graw_DFM-17_(Radiosonde)
[AUD_00000101T0524_403410000Hz.zip](https://github.com/projecthorus/radiosonde_auto_rx/files/12146916/AUD_00000101T0524_403410000Hz.zip)

**Comment by darksidelemm** [comment]
We are well aware of this, and it's been the case for quite a while now.
Is there something in this repository that I need to update regarding this?
