### ISSUE TITLE
Display old log to the web server page.

### ISSUE THREAD

**Issue by djecom1** [projecthorus/radiosonde_auto_rx#79]
Add to the local web page the possibility to read the old log (text and / or cartography).
(if possible...!!!)
Or find a way to convert log in .kml format to read it later (or without internet conection)

**Comment by darksidelemm** [comment]
There is a log file to KML converter script here:
https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/utils/log_to_kml.py
Note: This utility requires the fastkml and shapely libraries, which can be installed using:

sudo pip install fastkml shapely

If you run it with the default options (i.e. python log_to_kml.py) it'll read in *all* the sonde log files, and output the all into one kml file (sondes.kml). Run the script with --help to see the command line options.

It this sufficient?

**Comment by djecom1** [comment]
It's perfect ! Sorry, I didn't saw that script.. 
Thank you !
