### ISSUE TITLE
updating to 1.6.2

### ISSUE THREAD

**Issue by ly5p** [projecthorus/radiosonde_auto_rx#793]
after upgrade not starting: 

pi@raspberrypi:~/radiosonde_auto_rx/auto_rx $ python3 auto_rx.py
Traceback (most recent call last):
  File "auto_rx.py", line 53, in <module>
    from autorx.web import (
  File "/home/pi/radiosonde_auto_rx/auto_rx/autorx/web.py", line 30, in <module>
    from werkzeug.middleware.proxy_fix import ProxyFix
ModuleNotFoundError: No module named 'werkzeug.middleware'

==> /var/log/daemon.log <==
Aug  4 07:02:53 raspberrypi auto_rx[3798]: Traceback (most recent call last):
Aug  4 07:02:53 raspberrypi auto_rx[3798]:   File "/home/pi/radiosonde_auto_rx/auto_rx/auto_rx.py", line 53, in <module>
Aug  4 07:02:53 raspberrypi auto_rx[3798]:     from autorx.web import (
Aug  4 07:02:53 raspberrypi auto_rx[3798]:   File "/home/pi/radiosonde_auto_rx/auto_rx/autorx/web.py", line 30, in <module>
Aug  4 07:02:53 raspberrypi auto_rx[3798]:     from werkzeug.middleware.proxy_fix import ProxyFix
Aug  4 07:02:53 raspberrypi auto_rx[3798]: ModuleNotFoundError: No module named 'werkzeug.middleware'
Aug  4 07:02:53 raspberrypi systemd[1]: auto_rx.service: Main process exited, code=exited, status=1/FAILURE
Aug  4 07:02:53 raspberrypi systemd[1]: auto_rx.service: Failed with result 'exit-code'.

==> /var/log/syslog <==
Aug  4 07:02:53 raspberrypi auto_rx[3798]: Traceback (most recent call last):
Aug  4 07:02:53 raspberrypi auto_rx[3798]:   File "/home/pi/radiosonde_auto_rx/auto_rx/auto_rx.py", line 53, in <module>
Aug  4 07:02:53 raspberrypi auto_rx[3798]:     from autorx.web import (
Aug  4 07:02:53 raspberrypi auto_rx[3798]:   File "/home/pi/radiosonde_auto_rx/auto_rx/autorx/web.py", line 30, in <module>
Aug  4 07:02:53 raspberrypi auto_rx[3798]:     from werkzeug.middleware.proxy_fix import ProxyFix
Aug  4 07:02:53 raspberrypi auto_rx[3798]: ModuleNotFoundError: No module named 'werkzeug.middleware'
Aug  4 07:02:53 raspberrypi systemd[1]: auto_rx.service: Main process exited, code=exited, status=1/FAILURE
Aug  4 07:02:53 raspberrypi systemd[1]: auto_rx.service: Failed with result 'exit-code'.

**Comment by darksidelemm** [comment]
This is mentioned in the release notes: https://github.com/projecthorus/radiosonde_auto_rx/releases/tag/v1.6.2
