### ISSUE TITLE
update error  1.6.1 to 1.6.2 webserver issue

### ISSUE THREAD

**Issue by laarhoven1** [projecthorus/radiosonde_auto_rx#799]
after the gitt pull and update preforming radiosonde_auto_rx 1.6.1 to .1.6.2 webserver not start !!
useing noelec nesdr smart dongle.
 Dongel test dongle works fine but the webserver is not started.
 
![20230819_204315](https://github.com/projecthorus/radiosonde_auto_rx/assets/93873923/b0d15a0e-a740-4cd9-bbaa-f0225a885222)

what to do now? before radiosonde auto rx 1.6.1 works fine....

**Comment by darksidelemm** [comment]
This issue is described explicitly in the release notes: https://github.com/projecthorus/radiosonde_auto_rx/releases/tag/v1.6.2
Please read those.

**Comment by laarhoven1** [comment]
> This issue is described explicitly in the release notes: https://github.com/projecthorus/radiosonde_auto_rx/releases/tag/v1.6.2 Please read those.

thanks for the fix we are running again!
