### ISSUE TITLE
missing rtl-sdr binary makes auto_rx not start, but without error message 

### ISSUE THREAD

**Issue by wwortel** [projecthorus/radiosonde_auto_rx#801]
Spent much time finding out why the program wouldn't start anymore.
Cause was missing rtl-sdr binary.

To reset the USB dongle a routine is started in auto_rx/autorx/utils.py that calls, in the Linux OS, a binary 'rtl-sdr' that is provided by a package with that name.
But while calling this rtl-sdr, any error message output is suppressed because error output has been deviated to /dev/none.
In my PC as part of maintenance inadvertedly rtl-sdr had been removed.
Please add a test, before calling rtl-sdr in the OS, that it actually exists and, when not, produces an error message that says so.

The compilation and installation of all is perfectly possible without rtl-sdr being present as binary. So one is left clue-less.

**Comment by darksidelemm** [comment]
OK, this should be fairly easy to add somewhere at the point where the other utilities are checked for.
