### ISSUE TITLE
Feature request: MQTT upload

### ISSUE THREAD

**Issue by j0uni** [projecthorus/radiosonde_auto_rx#803]
I would like to have the data uploaded to my personal server through MQTT. 

I think it would open up more possibilites for many such as those who send high altitude balloons or want to analyze the information (by storing to database).

I've seen some code that included MQTT feature here but it seems to be removed?

**Comment by darksidelemm** [comment]
I've never included MQTT support, unsure where you saw that.
It's not really something i want to add into auto_rx itself.

auto_rx has a UDP broadcast output which you should be able to make use of with an external script to feed data into MQTT.
There's an example of receiving the UDP data here: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/utils/horus_udp_receiver_example.py

**Comment by j0uni** [comment]
Here is the feature from history:

https://github.com/projecthorus/radiosonde_auto_rx/pull/35

Btw: out of interest, why don't you want to add it? Is it because of python limitations?

**Comment by darksidelemm** [comment]
That PR dates back to when auto_rx looked a lot different to what it does now. 

At this stage it's mainly a time thing, I have other priorities like trying to add support for some new radiosonde types, and supporting additional receivers options. We already have a few options to get data out of auto_rx into other applications, so I'd prefer it if they get used. 
I'd be happy to accept a well-tested PR.
