### ISSUE TITLE
Email Test for Landing Alert Fails Silently

### ISSUE THREAD

**Issue by thetoivonen** [projecthorus/radiosonde_auto_rx#807]
When running `python -m autorx.email_notification` I get a launch alert and an encrypted launch alert but I never get a nearby landing alert.  In email_notification.py, it appears that a landing alert test is included, but it seems to fail silently.  Even when running the test with the `-v` switch there are no apparent errors.

Is the landing alert test just not fully implemented, or is something not working correctly on my end?

**Comment by darksidelemm** [comment]
Very possible i've broken something in the tests. I did make modifications so the landing alert only happens if the sonde first rises above some particular altitude, so that might have broken the tests.

**Comment by darksidelemm** [comment]
Yes, definitely a few things broken on the tests. I found an issue related to passing of dictionaries by reference that was probably breaking things.
Have pushed an update into the testing branch. Will leave this issue open until the fix gets properly released.

**Comment by thetoivonen** [comment]
I just submitted a PR that fixed things on my end.  The starting altitude was too low for it to send the landing alert.

**Comment by darksidelemm** [comment]
Fixed in 1.7.1
