### ISSUE TITLE
sonde minimum height display on historical

### ISSUE THREAD

**Issue by MikeTango** [projecthorus/radiosonde_auto_rx#815]
Hi,

after reviewing the code i think that min_height does not parse the actual lowest position data, instead assuming that the last frame is always the lowest. It gets labeled as "last observed height" in the table. If that's how it is done, is there a way of actually showing the lowest observed height? I'm trying to observe launches.

**Comment by darksidelemm** [comment]
I'm doing the last frame approach because thats the fastest way at this point. Other approaches mean parsing through more (possibly all) of the log file to determine the minimum altitude. For systems with lots of log file stored this may result in the historical page taking far too long to load.

**Comment by obi7zik** [comment]
> I'm doing the last frame approach because thats the fastest way at this point. Other approaches mean parsing through more (possibly all) of the log file to determine the minimum altitude. For systems with lots of log file stored this may result in the historical page taking far too long to load.

Would incorporating the maximum altitude and speed on the historical page potentially lead to longer loading times?

**Comment by darksidelemm** [comment]
The short answer is 'yes' - this will lead to much longer loading times as more of the log files will need to be parsed.
