### ISSUE TITLE
Older (weideband) iMet decoder (Nice to have)

### ISSUE THREAD

**Issue by zanco** [projecthorus/radiosonde_auto_rx#816]
About 5 times a week the older iMet's fly from different locations in the EU, none of them show on the sondehub page .

Is it possible to add support for those iMet's too ? They decode with the "regular" iMet decoder however they hava 80 kHz or a bit more bandwidth

![Afbeelding van WhatsApp op 2023-09-28 om 09 47 54](https://github.com/projecthorus/radiosonde_auto_rx/assets/4477734/e2aeacd6-1852-42d8-8b01-27c6f47afab0)
Here you see one on 404.500 which is "overtaken" by an RS41  signal.

Thanks,
Ben

**Comment by darksidelemm** [comment]
So the latest beta has a 'wideband_sondes' setting described here: https://github.com/projecthorus/radiosonde_auto_rx/wiki/Configuration-File-Changelog#version-163-in-beta

HOWEVER - note the caveats involved:
* You will not be able to decode both regular iMet sondes at the same time, and detection of other sonde types is likely to be extremely degraded. 
* Peak detection will not work - you have to set the frequencies in the always_scan list for them to be detected at all.

**Comment by darksidelemm** [comment]
Closing this as support for this (at least, the best i can do) is in 1.7.1
