### ISSUE TITLE
Add RTLSDR Product/Device ID Lookup Table.

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/radiosonde_auto_rx#82]
It's come to my attention that there are RTLSDRs out there with 'weird' product/device IDs.
i.e.:
Bus 001 Device 004: ID 1d19:1102 Dexatek Technology Ltd. DK mini DVB-T Dongle
Bus 001 Device 005: ID 0ccd:00b3 TerraTec Electronic GmbH NOXON DAB/DAB+ Stick

These devices don't get picked up by find_rtlsdr: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/autorx/utils.py#L385

There's probably a list of known IDs in the rtl-sdr source we can pull in and check against instead of doing the current check for 'RTL283*' that we do now.

**Comment by dbrooke** [comment]
either
https://github.com/steve-m/librtlsdr/blob/master/src/librtlsdr.c#L313
or
https://github.com/steve-m/librtlsdr/blob/master/rtl-sdr.rules
may be useful
