### ISSUE TITLE
msi2500, BG7YZF,... how to use as second SDR??

### ISSUE THREAD

**Issue by joni73** [projecthorus/radiosonde_auto_rx#822]
hi,

Is there anyeway to run BG7YZF as second SDR,...
... for example run two auto_rx process whit
diffrent config so second one could be used
 testing for example wideband_sondes = True ?

I tried to find some kinda emulator, there
must be,.. who tells first!

joni

**Comment by darksidelemm** [comment]
Sorry, the MSI-based SDRs are not supported in auto_rx at this time.
Currently we only support RTLSDR, and airspy units (via spyserver).
