### ISSUE TITLE
the problem stems from librtlsdr.git

### ISSUE THREAD

**Issue by Store9w2bws** [projecthorus/radiosonde_auto_rx#826]
https://github.com/projecthorus/radiosonde_auto_rx/wiki

hi this time when trying to download rtl-sdr doesn't work, for example
$ git clone https://github.com/steve-m/librtlsdr.git 

(the problem stems from librtlsdr.git, creating problems for new users to download. is this just a restriction sometimes it requires github password to download, to think the solution makes installation more time to find download from other networks.)

$ cd rtl-sdr (error)

(to enter rtl-sdr is not possible, which looks like librtlsdr.git) I use another path 
$ git clone git://git.osmocom.org/rtl-sdr.git )

$ mkdir build
$ cd build
$ cmake -DINSTALL_UDEV_RULES=ON -DDETACH_KERNEL_DRIVER=ON ../
$ sudo make install
$ sudo ldconfig

**Comment by darksidelemm** [comment]
I think the simpler fix here is replacing the line below git clone with:
```
$ cd librtlsdr
```
... which is what I've just done.

Thanks for picking it up.
