### ISSUE TITLE
WSL works

### ISSUE THREAD

**Issue by gvcallen** [projecthorus/radiosonde_auto_rx#828]
Hi Team,

Thank you so much for this awesome project!

I would just like to let you know that I successfully got it working under WSL, so the docs can be updated to reflect this. All that was required was to attached my RTLSDR via USB using the latest WSL method, and run the relevant commands (rtl_test and the auto_rx script itself) under sudo, and everything worked without hassle.

Regards,
Gary

**Comment by darksidelemm** [comment]
OK, I've made a note about that!
