### ISSUE TITLE
rtl_power call failed with return code -2

### ISSUE THREAD

**Issue by michaelself10** [projecthorus/radiosonde_auto_rx#840]
I want to make sure this error code is nothing serious, or anything at all. Sometimes when I quit the code (ctrl+c), I get the following error message...
![Screenshot 2023-12-29 224203](https://github.com/projecthorus/radiosonde_auto_rx/assets/151393601/fb3b167c-f63a-4e6b-8e4f-39281f31b116)

**Comment by darksidelemm** [comment]
That's fine - this is because the ctrl-c has probably killed that rtl_power subprocess, resulting in an abnormal return code. Feel free to close the issue if that has answered your questions.

**Comment by michaelself10** [comment]
> That's fine - this is because the ctrl-c has probably killed that rtl_power subprocess, resulting in an abnormal return code. Feel free to close the issue if that has answered your questions.

Thanks! Just making sure it is all good, I will close the issue now.
