### ISSUE TITLE
Coverage calculation - how does it work?

### ISSUE THREAD

**Issue by MikeTango** [projecthorus/radiosonde_auto_rx#843]
Hi, 

i am looking at the plots for my home setup and noticed that entire paths of sondes are not in the "coverage" polygon despite being completely logged. Is there any way to fix that?

regards,

MT
![Screenshot 2024-01-01 at 11-13-01 Old 💜 Dreamcatcher](https://github.com/projecthorus/radiosonde_auto_rx/assets/3368005/a72c0aab-929a-4d58-9bb8-45e09e5ebd6f)

**Comment by darksidelemm** [comment]
The coverage polygon only uses first and last positions, not every single position. This is to avoid having to read and parse every entry of what might be a very large number of log files.

**Comment by MikeTango** [comment]
Ok, that makes a bit of sense because mostly the balloons don't boomerang, but leaves these odd gaps. How do the single lines and very thin spikes come about? Shouldn't the polygon connect the extremes?
