### ISSUE TITLE
Always-scan values always showing peak

### ISSUE THREAD

**Issue by michaelself10** [projecthorus/radiosonde_auto_rx#850]
Recently my scan plot has been showing continuous "peaks" at the frequencies that I have in the always-scan section of the config file. When I add more values to that list, they also show up as "peaks". I am not too sure what has happened. Here is what my scan plot looks like.

I have always-scan for 401.0 and 403.01, and the threshold for peaks is 5 dB (but it has been at 4 dB and didn't have this problem).
![Screenshot 2024-01-06 143604](https://github.com/projecthorus/radiosonde_auto_rx/assets/151393601/14bf034b-dc58-438d-8fd8-1017b8591375)

**Comment by darksidelemm** [comment]
This is intentional - the always_scan entries insert 'peak' entries into the scanning code, which will show up on the spectrum plot like you see.
