### ISSUE TITLE
Threshold settings adjustable ?

### ISSUE THREAD

**Issue by videobuff** [projecthorus/radiosonde_auto_rx#870]
Is it possible to lower the Threshold ?
I have a new RTL_SDR dongle V4, and besides of the spike at 403.2 due to the internal 28Mhz clock , the noise floor leel is at least 6 db below the green line of the threshold.
Screenshot of today

<img width="1406" alt="Scherm­afbeelding 2024-04-18 om 01 07 59" src="https://github.com/projecthorus/radiosonde_auto_rx/assets/3132953/1525d315-5c90-4f0f-9c30-81990fb7ed5f">

**Comment by darksidelemm** [comment]
The short answer is 'yes' - and it's this setting: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/station.cfg.example#L528
The default is 10 dB, and that's what the green line is set to: 10 dB above the median power level from the scan, which is an approximation of your noise floor.

The decoders generally need about 10 dB SNR to decode reliably, to setting it lower doesn't usually help matters.
