### ISSUE TITLE
Bias on RTL-SDR V4

### ISSUE THREAD

**Issue by OK1SLM** [projecthorus/radiosonde_auto_rx#871]
Add support bias tee  on RTL-SDR v4

**Comment by darksidelemm** [comment]
This should be working already? 

Within the docker image we're already using a version of librtlsdr (and the corresponding utilities) that supports the RTLSDR v4. 
If you're not using the docker image, then it's up to you to ensure you have installed a version of librtlsdr (either from your package manager or from source) that supports the v4.

**Comment by bddvlpr** [comment]
Works for a brand new RTL-SDR v4 on the latest Docker image so this shouldn't be a problem.
