### ISSUE TITLE
Multiple SCAN with 2 SDR and 2 antennas

### ISSUE THREAD

**Issue by Pepan-1** [projecthorus/radiosonde_auto_rx#873]
Hii,

I have two SDR scanners, each with its own YAGI antenna towards the launch site. No single common antenna with a splitter. Is it possible for each tuner to scan and remain clipped to that tuner after finding a signal?

At this moment, the first SDR is scanning and the second is waiting. After finding the probe signal, the first SDR transfers the decoding task to the waiting second one and continues scanning. This is undesirable. Because the SDR1 antenna receives the starting point 1, but the SDR2 does not. The reverse also applies. SDR2 receives starting location 2, but not 1.

I am a newbie, please excuse my possibly stupid question.

P.

**Comment by darksidelemm** [comment]
The current behaviour is the intended behaviour, and not something I plan on changing anytime soon. 
The first SDR is not really decoding at the point where the sonde is being detected, it is just looking for a packet header. 

If you want to be sure you are receiving the sonde right from the start, then the best bet is going to be to move to add more SDRs so you can dedicate one of them to a known launch site frequency, or move to an AIrspy-based system where you can do the same with one SDR.
