### ISSUE TITLE
Dedicated only_scan/never_scan per SDR

### ISSUE THREAD

**Issue by EightEFI** [projecthorus/radiosonde_auto_rx#884]
I wanted to dedicate few directional antennas to two directions, which are over 90 degrees apart. I just discovered after testing that this seems not be possible? That both SDRs would work independently with their own lists to scan.

**Comment by darksidelemm** [comment]
For this situation you are probably better off running two instances of radiosonde_auto_rx, one for each SDR. 
I'd rather not complicate the configuration settings any more than they already are!

**Comment by EightEFI** [comment]
Thank you for quick reply! That is the route I am now going towards.
