### ISSUE TITLE
Habitat Listener Info re-upload

### ISSUE THREAD

**Issue by kikosgc** [projecthorus/radiosonde_auto_rx#90]
What about adding a re-upload Listener information every, maybe 6 hours? 
![image](https://user-images.githubusercontent.com/30269365/46472889-e563f300-c7de-11e8-9a16-b479f305b180.png)

This way we are sure that the station is fully operational...

Thanks for your work!

**Comment by darksidelemm** [comment]
Should be easy enough... Will add it in when I get time...

**Comment by darksidelemm** [comment]
Fixed in https://github.com/projecthorus/radiosonde_auto_rx/commit/ea51bbc0f1a44f014a426bf1002289cb43b25a14
