### ISSUE TITLE
flask_thread(host="0.0.0.0", port=5000)

### ISSUE THREAD

**Issue by phirippu** [projecthorus/radiosonde_auto_rx#900]
Please update web.py, where port 5000 is hardcoded.

**Comment by darksidelemm** [comment]
It's not hard-coded, that argument is just a default, and gets overwritten with whatever is in this configuration setting: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/station.cfg.example#L473

**Comment by phirippu** [comment]
I got it working by removing the .pyc files. Indeed, it works.
