### ISSUE TITLE
Shutdown Raspberry Pi in Auto_RX web interface

### ISSUE THREAD

**Issue by PC9DB** [projecthorus/radiosonde_auto_rx#927]
To safely shutdown a headless Pi running Auto_RX, one has to establish for example a SSH connection to the Pi and then shut it down.
It would be handy to have a "Shutdown Pi" option in the control page of the web interface.

**Comment by darksidelemm** [comment]
I'm not sure this is going to be possible without auto_rx running as root. It definitely shouldn't be possible from within the docker image.

**Comment by PC9DB** [comment]
Thanks for your comment Mark. It would be a handy option, especially when using a RPi in a car.
But there are other options for example with a simple switch programmed to shut down the pi.

Regards,
Mark
