### ISSUE TITLE
Station altitude in config file

### ISSUE THREAD

**Issue by SerBrynden** [projecthorus/radiosonde_auto_rx#959]
In the station.cfg file, is the recevier station altitude supposed to be above ground or above sea level?

**Comment by darksidelemm** [comment]
This is above-mean-sea-level. 
It's used to calculate the range/azimuth and (importantly) elevation to a sonde, so it needs to be AMSL, as that's what the sondes report.

**Comment by SerBrynden** [comment]
Thank you very much!  It might be worse specifying that in the config file.
