### ISSUE TITLE
Issue with scan plot on 1.8.0

### ISSUE THREAD

**Issue by lincdeckard** [projecthorus/radiosonde_auto_rx#960]
Hello, after update the scan plot now shows up like this: 

![image](https://github.com/user-attachments/assets/7b4b6cef-27b6-4c48-8347-e015f4a79ee2)

Any thoughts?

Best,
Carlos

**Comment by darksidelemm** [comment]
This is pretty much what is expected. We've removed the section header above the scan plot, and the frequency scale is now cleaned up.

**Comment by lincdeckard** [comment]
I mean, the plot isn't correct. It's only noise and seems to be mirrored 3 times. It doesn't correspond to the actual RF spectrum.

**Comment by darksidelemm** [comment]
Yes, quite possibly. RTLSDR scanning hasn't changed in this release, so I'm not sure why that would have happened. Perhaps check your RF setup? Maybe try switching back to one of the SDRs and see if that makes a difference?

**Comment by lincdeckard** [comment]
Ah that was it, I needed to reboot the raspberry to reset both RTL dongles. It's working fine now, thanks!
