### ISSUE TITLE
SpyServer tasks crashing

### ISSUE THREAD

**Issue by Feuerwerko** [projecthorus/radiosonde_auto_rx#966]
Hello,

I just set up a spyserver + autorx configuration on my rpi 4 that used to run an RTLSDR.
When using the recommended spyserver config, 1-2 tasks crash at the beginning while the others work fine.

Heres the logs in the sidebar when restarting autorx:
After restart 1 (only 1 out of 4 tasks crashed):
![image](https://github.com/user-attachments/assets/46dbdd42-f5ca-42ec-88d8-c0fb2271cdfb)
After restart 2 (2 out of 4 tasks crashed):
![image](https://github.com/user-attachments/assets/696c8099-dc39-41a5-963b-e69dd4a40ffe)

Could this be a performance issue? Theres some other stuff running on the pi that shouldnt put too much load on it tho.

**Comment by Feuerwerko** [comment]
This seems to be the issue. SDR++ receives the signals just fine when I remove the frequency presets:
![image](https://github.com/user-attachments/assets/41f88aef-e61e-4e12-81aa-43f9c9388f59)

**Comment by Feuerwerko** [comment]
Okay I just tried the spyserver config from the wiki. Didnt see it before, my mistake.
When I try that config, only one of the tasks crashes and it continues receiving fine.
![image](https://github.com/user-attachments/assets/46dbdd42-f5ca-42ec-88d8-c0fb2271cdfb)

**Comment by ke5gdb** [comment]
Are you using v1.8.0? If so, try updating to the latest testing version. There was an issue identified a few hours ago pertaining to return code 124 (timeout error) that was patched. 

You should also consider using KA9Q-Radio.

**Comment by Feuerwerko** [comment]
Yes, I just updated.
I was thinking of using KA9Q Radio but it seems a little experimental and poorly documented.
Are there any big advantages that KA9Q radio has over spyserver?

**Comment by ke5gdb** [comment]
Check the install notes here: https://github.com/projecthorus/radiosonde_auto_rx/wiki/KA9Q%E2%80%90Radio-Setup-Notes

It's just a better platform. It's more efficient, actively developed, and open source. However, before you consider making the change, I'm curious if updating to the latest testing version fixed the issue.

**Comment by Feuerwerko** [comment]
Switching to testing did indeed work. No errors now.
Im gonna try switching to KA9Q and see if it works.
