### ISSUE TITLE
Pushbullet support?

### ISSUE THREAD

**Issue by l0r-e** [projecthorus/radiosonde_auto_rx#970]
Hello, i was wondering if there was any possibility to have more alerts directly from auto_rx, instead of classic emails, made for those not so much terminal familiar. 

I think their api's easy to work with. I already tried by adding a kind of alerting script (just for ascending sondes) but nothing, i am far too unexperienced to do it myself.

**Comment by darksidelemm** [comment]
I don't want to add more alerting service integrations into auto_rx, sorry.

auto_rx already emits all telemetry it receives via UDP broadcast. 
If someone wants a particular alerting system, then I recommend they make use of this output and write their own alerting software based on it.

**Comment by l0r-e** [comment]
oh, okay. fantastic.
Looks like i missed that part! thanks for the quick response :)

**Comment by buttim** [comment]
Someone already built something to do what you want I think. Not tested personally
https://github.com/ch3p4ll3/radiosonde_auto_rx_notifier

**Comment by l0r-e** [comment]
Oh cool, thanks

**Comment by darksidelemm** [comment]
That's a neat project! I think i need to start a list of 'auto_rx add-on software' like this, so they can be more easily found...
